// Convenience aliases over the generated OpenAPI types.
// Import domain types from here (e.g. `import type { Game } from '@/api-types'`)
// rather than reaching into generated.ts, which is regenerated by `pnpm gen:api`.
import type { components } from './generated'

export type Schemas = components['schemas']

export type Role = Schemas['Role']
export type User = Schemas['User']
export type LoginRequest = Schemas['LoginRequest']
export type LoginResponse = Schemas['LoginResponse']
export type RefreshResponse = Schemas['RefreshResponse']
export type Game = Schemas['Game']
export type TestModel = Schemas['TestModel']
export type Opportunity = Schemas['Opportunity']
export type TestReport = Schemas['TestReport']
export type ApiError = Schemas['ApiError']
