// Generated by scripts/gen-player-game-api.mjs. Do not edit by hand.
export interface paths {
  '/player/games/{gameId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Detalhes de um jogo para o jogador
     * @description Tela 15. Banner, disponibilidade, jogadores e testes abertos.
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          gameId: components['parameters']['GameId']
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Jogo na visão do jogador */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['PlayerGame']
          }
        }
        404: components['responses']['NotFound']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/player/games/{gameId}/tests': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Testes de um jogo disponíveis para o jogador */
    get: {
      parameters: {
        query?: {
          /** @description Itens por página. */
          limit?: components['parameters']['Limit']
          /** @description Cursor opaco devolvido como `nextCursor` na página anterior. */
          cursor?: components['parameters']['Cursor']
        }
        header?: never
        path: {
          gameId: components['parameters']['GameId']
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Página de testes elegíveis */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['PlayerTestList']
          }
        }
        404: components['responses']['NotFound']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/player/tests/{testId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Detalhe de um teste para o jogador
     * @description RN-01 (Tela 15): `cta` é **calculado no backend** —
     *     `start`, `continue`, `completed`, `in_review`, `downloading` ou
     *     `unavailable`. A UI apenas renderiza o que veio.
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          testId: components['parameters']['TestId']
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Teste na visão do jogador */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['PlayerTest']
          }
        }
        404: components['responses']['NotFound']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/player/participations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Meus testes
     * @description Rota própria, e **não** `/player/tests/mine`, de propósito: o segmento
     *     literal `mine` colidiria com o parâmetro de `/player/tests/{testId}`. Em
     *     roteadores que casam o segmento dinâmico primeiro, `mine` cairia no
     *     `{testId}` e falharia na validação de UUID. Separar a rota remove a
     *     ambiguidade em vez de depender da ordem de declaração.
     */
    get: {
      parameters: {
        query?: {
          /** @description Itens por página. */
          limit?: components['parameters']['Limit']
          /** @description Cursor opaco devolvido como `nextCursor` na página anterior. */
          cursor?: components['parameters']['Cursor']
          status?: components['schemas']['ParticipationStatus']
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Página de participações do jogador */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ParticipationList']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/player/tests/{testId}/participations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Entrar em um teste
     * @description Reserva a vaga. Valida elegibilidade, vagas restantes, prazo e
     *     compatibilidade **no servidor** — a checagem feita para montar o feed
     *     não é suficiente, porque o estado pode ter mudado desde então.
     *
     *     RN-02 (Tela 14): não é permitido iniciar duas participações simultâneas
     *     no mesmo teste. Repetição com a mesma `Idempotency-Key` devolve a
     *     participação existente; sem a chave, um segundo pedido responde `409`.
     */
    post: {
      parameters: {
        query?: never
        header: {
          /**
           * @description Chave única por tentativa, gerada pelo cliente (UUID). Repetir a chave
           *     **reproduz a resposta original** em vez de executar a operação de novo.
           */
          'Idempotency-Key': components['parameters']['IdempotencyKey']
        }
        path: {
          testId: components['parameters']['TestId']
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Participação criada */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Participation']
          }
        }
        403: components['responses']['Forbidden']
        404: components['responses']['NotFound']
        /** @description Já participa, vagas esgotadas, teste expirado ou dispositivo incompatível */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ErrorEnvelope']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/participations/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Obter participação */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: components['parameters']['Id']
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Participação */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Participation']
          }
        }
        404: components['responses']['NotFound']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/games/{id}/achievements': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Conquistas configuradas do jogo */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: components['parameters']['Id']
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Conquistas do jogo */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              data: components['schemas']['Achievement'][]
            }
          }
        }
        404: components['responses']['NotFound']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/games/{id}/specs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Especificações técnicas do jogo */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: components['parameters']['Id']
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Especificações */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['GameSpecs']
          }
        }
        404: components['responses']['NotFound']
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/player/achievements': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Conquistas do jogador */
    get: {
      parameters: {
        query?: {
          /** @description Itens por página. */
          limit?: components['parameters']['Limit']
          /** @description Cursor opaco devolvido como `nextCursor` na página anterior. */
          cursor?: components['parameters']['Cursor']
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Página de conquistas */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['PlayerAchievementList']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/games/{gameId}/community/posts': {
    parameters: {
      query?: never
      header?: never
      path: {
        gameId: components['parameters']['GameId']
      }
      cookie?: never
    }
    /** Publicações da comunidade do jogo */
    get: {
      parameters: {
        query?: {
          /** @description Itens por página. */
          limit?: components['parameters']['Limit']
          /** @description Cursor opaco devolvido como `nextCursor` na página anterior. */
          cursor?: components['parameters']['Cursor']
        }
        header?: never
        path: {
          gameId: components['parameters']['GameId']
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Página de publicações */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['CommunityPostList']
          }
        }
        404: components['responses']['NotFound']
      }
    }
    put?: never
    /**
     * Publicar na comunidade do jogo
     * @description RN-04 (Tela 15): sujeito a moderação e vínculo com o jogo.
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          gameId: components['parameters']['GameId']
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateCommunityPostRequest']
        }
      }
      responses: {
        /** @description Publicação criada */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['CommunityPost']
          }
        }
        403: components['responses']['Forbidden']
        404: components['responses']['NotFound']
        422: components['responses']['ValidationError']
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/games/{gameId}/reviews': {
    parameters: {
      query?: never
      header?: never
      path: {
        gameId: components['parameters']['GameId']
      }
      cookie?: never
    }
    /** Avaliações do jogo */
    get: {
      parameters: {
        query?: {
          /** @description Itens por página. */
          limit?: components['parameters']['Limit']
          /** @description Cursor opaco devolvido como `nextCursor` na página anterior. */
          cursor?: components['parameters']['Cursor']
        }
        header?: never
        path: {
          gameId: components['parameters']['GameId']
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Página de avaliações */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ReviewList']
          }
        }
        404: components['responses']['NotFound']
      }
    }
    put?: never
    /**
     * Avaliar o jogo
     * @description Só quem concluiu ao menos uma sessão válida do jogo pode avaliar, e uma
     *     vez por jogador.
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          gameId: components['parameters']['GameId']
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateReviewRequest']
        }
      }
      responses: {
        /** @description Avaliação criada */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Review']
          }
        }
        /** @description Sem sessão válida concluída neste jogo */
        403: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ErrorEnvelope']
          }
        }
        /** @description Jogador já avaliou este jogo */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ErrorEnvelope']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    PlayerGame: {
      game: components['schemas']['Game']
      playersTotal?: number
      openTests: number
      maxRewardCents?: number | null
      specs?: components['schemas']['GameSpecs']
    }
    Game: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      organizationId: string
      title: string
      slug: string
      description?: string | null
      genre?: string | null
      platform?: string | null
      status: components['schemas']['GameStatus']
      /** Format: uri */
      coverUrl?: string | null
      /** Format: uri */
      bannerUrl?: string | null
      metrics?: components['schemas']['GameMetrics']
      /** Format: date-time */
      createdAt: string
      /** Format: date-time */
      updatedAt: string
    }
    /** @enum {string} */
    GameStatus: 'draft' | 'active' | 'archived'
    /**
     * @description RN-03 (Tela 03): agregados a partir dos testes do jogo, calculados no
     *     backend.
     */
    GameMetrics: {
      testsTotal?: number
      testsActive?: number
      sessionsValid?: number
      playersTotal?: number
      /** Format: float */
      averageRating?: number | null
    }
    GameSpecs: {
      minimumRequirements?: {
        [key: string]: string
      }
      recommendedRequirements?: {
        [key: string]: string
      }
      supportedPlatforms?: components['schemas']['Platform'][]
      languages?: string[]
    }
    /** @enum {string} */
    Platform: 'windows' | 'macos' | 'linux' | 'android' | 'ios' | 'web'
    /**
     * @description Envelope único de erro da API. Serializado exclusivamente pelo
     *     `HttpExceptionFilter` — nenhum controller monta erro à mão.
     */
    ErrorEnvelope: {
      /** @example 422 */
      statusCode: number
      code: components['schemas']['ErrorCode']
      /** @example Dados inválidos */
      message: string
      /**
       * @description Mensagem por campo, presente em falhas de validação.
       * @example {
       *       "title": "Título obrigatório"
       *     }
       */
      fieldErrors?: {
        [key: string]: string
      }
      /** @description Correlaciona a resposta com os logs estruturados. */
      requestId: string
    }
    /** @enum {string} */
    ErrorCode:
      | 'VALIDATION_ERROR'
      | 'UNAUTHORIZED'
      | 'FORBIDDEN'
      | 'NOT_FOUND'
      | 'CONFLICT'
      | 'TOO_MANY_REQUESTS'
      | 'UNPROCESSABLE_ENTITY'
      | 'INTERNAL_ERROR'
    PlayerTestList: {
      data: components['schemas']['PlayerTest'][]
      nextCursor: string | null
    }
    PlayerTest: {
      modelKey?: components['schemas']['TestModelKey']
      participation?: components['schemas']['Participation'] | null
    } & WithRequired<components['schemas']['FeedItem'], 'testId' | 'gameId' | 'cta' | 'disabled'>
    FeedItem: {
      /** Format: uuid */
      testId: string
      /** Format: uuid */
      gameId: string
      title: string
      genre?: string | null
      /** Format: uri */
      coverUrl?: string | null
      rewardCents?: number | null
      durationMinutes?: number | null
      spotsLeft?: number | null
      /** Format: date-time */
      expiresAt?: string | null
      platforms?: components['schemas']['Platform'][]
      cta: components['schemas']['TestCta']
      /**
       * @description 'RN-03 (Tela 14): incompatível ou indisponível aparece desabilitado
       *     com motivo, em vez de sumir sem explicação.'
       */
      disabled: boolean
      disabledReason?: string | null
      /**
       * @description Item pago. Sempre `false` nesta fase. Quando o impulsionamento
       *     voltar, a UI **precisa** rotular o item — publicidade não
       *     identificada é questão regulatória.
       * @default false
       */
      promoted: boolean
    }
    /**
     * @description RN-01 (Tela 15): calculado no backend, nunca inferido na UI.
     * @enum {string}
     */
    TestCta: 'start' | 'continue' | 'completed' | 'in_review' | 'downloading' | 'unavailable'
    /** @enum {string} */
    TestModelKey: 'free_exploration_telemetry' | 'free_exploration' | 'ab_test' | 'ab_test_images'
    Participation: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      testId: string
      /** Format: uuid */
      gameId?: string
      status: components['schemas']['ParticipationStatus']
      /** Format: uuid */
      currentSessionId?: string | null
      /** @description RN-02 (Tela 13): ponto de retomada permitido pelo modelo. */
      resumePoint?: string | null
      consentsGranted?: boolean
      build?: components['schemas']['Build']
      /** Format: date-time */
      startedAt?: string | null
      /** Format: date-time */
      completedAt?: string | null
    }
    /**
     * @description Máquina de estados da participação, alinhada às telas do fluxo do
     *     jogador: `tutorial` (Tela 16), `playing` (Tela 17), `form_pending`
     *     (Tela 18) e `in_review` (Tela 19).
     * @enum {string}
     */
    ParticipationStatus:
      | 'reserved'
      | 'tutorial'
      | 'downloading'
      | 'ready'
      | 'playing'
      | 'form_pending'
      | 'in_review'
      | 'completed'
      | 'rejected'
      | 'abandoned'
    Build: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      testId?: string
      /** @enum {string} */
      status: 'uploading' | 'processing' | 'validated' | 'failed'
      platform?: components['schemas']['Platform']
      version?: string | null
      sizeBytes?: number | null
      checksum?: string | null
      /**
       * @description Lista de etapas, **não** um booleano. A leitura do manifesto do
       *     Orbit Plug-in entra aqui como mais uma etapa quando voltar ao
       *     escopo, sem alterar o formato.
       */
      validationSteps: components['schemas']['ValidationStep'][]
      /** @description RN-05 (Tela 08): diz o que corrigir para tentar de novo. */
      failureReason?: string | null
      /** Format: date-time */
      createdAt?: string
    }
    ValidationStep: {
      /** @enum {string} */
      key: 'checksum' | 'malware_scan' | 'metadata' | 'platform_support'
      /** @enum {string} */
      status: 'pending' | 'running' | 'passed' | 'failed' | 'skipped'
      message?: string | null
    }
    ParticipationList: {
      data: components['schemas']['Participation'][]
      nextCursor: string | null
    }
    Achievement: {
      key: string
      name: string
      description?: string
      /** Format: uri */
      iconUrl?: string | null
    }
    PlayerAchievementList: {
      data: components['schemas']['PlayerAchievement'][]
      nextCursor: string | null
    }
    PlayerAchievement: {
      achievement: components['schemas']['Achievement']
      unlocked: boolean
      /** Format: date-time */
      unlockedAt?: string | null
      /** Format: float */
      progress?: number | null
    }
    CommunityPostList: {
      data: components['schemas']['CommunityPost'][]
      nextCursor: string | null
    }
    CommunityPost: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      gameId: string
      /** Format: uuid */
      authorUserId?: string
      authorDisplayName: string
      body: string
      /** @enum {string} */
      status: 'visible' | 'hidden' | 'pinned'
      /** Format: date-time */
      createdAt: string
    }
    CreateCommunityPostRequest: {
      body: string
    }
    ReviewList: {
      data: components['schemas']['Review'][]
      nextCursor: string | null
      /** Format: float */
      averageRating?: number | null
    }
    Review: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      gameId: string
      /** Format: uuid */
      authorUserId?: string
      authorDisplayName: string
      rating: number
      body?: string | null
      /** Format: date-time */
      createdAt: string
    }
    CreateReviewRequest: {
      rating: number
      body?: string
    }
  }
  responses: {
    /**
     * @description Recurso inexistente — ou pertencente a outra organização. As duas
     *     situações respondem igual, de propósito, para não vazar existência.
     */
    NotFound: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['ErrorEnvelope']
      }
    }
    /** @description Papel sem permissão para esta ação */
    Forbidden: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['ErrorEnvelope']
      }
    }
    /** @description Dados inválidos, com erro por campo em `fieldErrors` */
    ValidationError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['ErrorEnvelope']
      }
    }
  }
  parameters: {
    GameId: string
    /** @description Itens por página. */
    Limit: number
    /** @description Cursor opaco devolvido como `nextCursor` na página anterior. */
    Cursor: string
    TestId: string
    /**
     * @description Chave única por tentativa, gerada pelo cliente (UUID). Repetir a chave
     *     **reproduz a resposta original** em vez de executar a operação de novo.
     */
    IdempotencyKey: string
    Id: string
  }
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
type WithRequired<T, K extends keyof T> = T & {
  [P in K]-?: T[P]
}
export type operations = Record<string, never>
