/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as PlayerIndexRouteImport } from './routes/player/index'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as PlayerGamesIndexRouteImport } from './routes/player/games/index'
import { Route as PlayerGamesIdRouteImport } from './routes/player/games/$id'
import { Route as PlayerReportsIndexRouteImport } from './routes/player/reports/index'
import { Route as StudioGamesIndexRouteImport } from './routes/studio/games/index'
import { Route as StudioGamesIdRouteImport } from './routes/studio/games/$id'
import { Route as StudioGamesNewRouteImport } from './routes/studio/games/new'
import { Route as StudioReportsIndexRouteImport } from './routes/studio/reports/index'
import { Route as StudioTestsIndexRouteImport } from './routes/studio/tests/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIndexRoute = PlayerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayerRoute,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const PlayerGamesIndexRoute = PlayerGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerGamesIdRoute = PlayerGamesIdRouteImport.update({
  id: '/games/$id',
  path: '/games/$id',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerReportsIndexRoute = PlayerReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => PlayerRoute,
} as any)
const StudioGamesIndexRoute = StudioGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioGamesIdRoute = StudioGamesIdRouteImport.update({
  id: '/games/$id',
  path: '/games/$id',
  getParentRoute: () => StudioRoute,
} as any)
const StudioGamesNewRoute = StudioGamesNewRouteImport.update({
  id: '/games/new',
  path: '/games/new',
  getParentRoute: () => StudioRoute,
} as any)
const StudioReportsIndexRoute = StudioReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioTestsIndexRoute = StudioTestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => StudioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/player': typeof PlayerRouteWithChildren
  '/studio': typeof StudioRouteWithChildren
  '/player/': typeof PlayerIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/player/games/$id': typeof PlayerGamesIdRoute
  '/studio/games/$id': typeof StudioGamesIdRoute
  '/studio/games/new': typeof StudioGamesNewRoute
  '/player/games/': typeof PlayerGamesIndexRoute
  '/player/reports/': typeof PlayerReportsIndexRoute
  '/studio/games/': typeof StudioGamesIndexRoute
  '/studio/reports/': typeof StudioReportsIndexRoute
  '/studio/tests/': typeof StudioTestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/player': typeof PlayerIndexRoute
  '/studio': typeof StudioIndexRoute
  '/player/games/$id': typeof PlayerGamesIdRoute
  '/studio/games/$id': typeof StudioGamesIdRoute
  '/studio/games/new': typeof StudioGamesNewRoute
  '/player/games': typeof PlayerGamesIndexRoute
  '/player/reports': typeof PlayerReportsIndexRoute
  '/studio/games': typeof StudioGamesIndexRoute
  '/studio/reports': typeof StudioReportsIndexRoute
  '/studio/tests': typeof StudioTestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/player': typeof PlayerRouteWithChildren
  '/studio': typeof StudioRouteWithChildren
  '/player/': typeof PlayerIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/player/games/$id': typeof PlayerGamesIdRoute
  '/studio/games/$id': typeof StudioGamesIdRoute
  '/studio/games/new': typeof StudioGamesNewRoute
  '/player/games/': typeof PlayerGamesIndexRoute
  '/player/reports/': typeof PlayerReportsIndexRoute
  '/studio/games/': typeof StudioGamesIndexRoute
  '/studio/reports/': typeof StudioReportsIndexRoute
  '/studio/tests/': typeof StudioTestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/player'
    | '/studio'
    | '/player/'
    | '/studio/'
    | '/player/games/$id'
    | '/studio/games/$id'
    | '/studio/games/new'
    | '/player/games/'
    | '/player/reports/'
    | '/studio/games/'
    | '/studio/reports/'
    | '/studio/tests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/player'
    | '/studio'
    | '/player/games/$id'
    | '/studio/games/$id'
    | '/studio/games/new'
    | '/player/games'
    | '/player/reports'
    | '/studio/games'
    | '/studio/reports'
    | '/studio/tests'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/player'
    | '/studio'
    | '/player/'
    | '/studio/'
    | '/player/games/$id'
    | '/studio/games/$id'
    | '/studio/games/new'
    | '/player/games/'
    | '/player/reports/'
    | '/studio/games/'
    | '/studio/reports/'
    | '/studio/tests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PlayerRoute: typeof PlayerRouteWithChildren
  StudioRoute: typeof StudioRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/': {
      id: '/player/'
      path: '/'
      fullPath: '/player/'
      preLoaderRoute: typeof PlayerIndexRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/player/games/': {
      id: '/player/games/'
      path: '/games'
      fullPath: '/player/games/'
      preLoaderRoute: typeof PlayerGamesIndexRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/games/$id': {
      id: '/player/games/$id'
      path: '/games/$id'
      fullPath: '/player/games/$id'
      preLoaderRoute: typeof PlayerGamesIdRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/player/reports/': {
      id: '/player/reports/'
      path: '/reports'
      fullPath: '/player/reports/'
      preLoaderRoute: typeof PlayerReportsIndexRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/studio/games/': {
      id: '/studio/games/'
      path: '/games'
      fullPath: '/studio/games/'
      preLoaderRoute: typeof StudioGamesIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/games/$id': {
      id: '/studio/games/$id'
      path: '/games/$id'
      fullPath: '/studio/games/$id'
      preLoaderRoute: typeof StudioGamesIdRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/games/new': {
      id: '/studio/games/new'
      path: '/games/new'
      fullPath: '/studio/games/new'
      preLoaderRoute: typeof StudioGamesNewRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/reports/': {
      id: '/studio/reports/'
      path: '/reports'
      fullPath: '/studio/reports/'
      preLoaderRoute: typeof StudioReportsIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/tests/': {
      id: '/studio/tests/'
      path: '/tests'
      fullPath: '/studio/tests/'
      preLoaderRoute: typeof StudioTestsIndexRouteImport
      parentRoute: typeof StudioRoute
    }
  }
}

interface PlayerRouteChildren {
  PlayerIndexRoute: typeof PlayerIndexRoute
  PlayerGamesIdRoute: typeof PlayerGamesIdRoute
  PlayerGamesIndexRoute: typeof PlayerGamesIndexRoute
  PlayerReportsIndexRoute: typeof PlayerReportsIndexRoute
}

const PlayerRouteChildren: PlayerRouteChildren = {
  PlayerIndexRoute: PlayerIndexRoute,
  PlayerGamesIdRoute: PlayerGamesIdRoute,
  PlayerGamesIndexRoute: PlayerGamesIndexRoute,
  PlayerReportsIndexRoute: PlayerReportsIndexRoute,
}

const PlayerRouteWithChildren =
  PlayerRoute._addFileChildren(PlayerRouteChildren)

interface StudioRouteChildren {
  StudioIndexRoute: typeof StudioIndexRoute
  StudioGamesIdRoute: typeof StudioGamesIdRoute
  StudioGamesNewRoute: typeof StudioGamesNewRoute
  StudioGamesIndexRoute: typeof StudioGamesIndexRoute
  StudioReportsIndexRoute: typeof StudioReportsIndexRoute
  StudioTestsIndexRoute: typeof StudioTestsIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioIndexRoute: StudioIndexRoute,
  StudioGamesIdRoute: StudioGamesIdRoute,
  StudioGamesNewRoute: StudioGamesNewRoute,
  StudioGamesIndexRoute: StudioGamesIndexRoute,
  StudioReportsIndexRoute: StudioReportsIndexRoute,
  StudioTestsIndexRoute: StudioTestsIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PlayerRoute: PlayerRouteWithChildren,
  StudioRoute: StudioRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
