/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as PlayerIndexRouteImport } from './routes/player/index'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as StudioGamesIndexRouteImport } from './routes/studio/games/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIndexRoute = PlayerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayerRoute,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioGamesIndexRoute = StudioGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => StudioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/player': typeof PlayerRouteWithChildren
  '/studio': typeof StudioRouteWithChildren
  '/player/': typeof PlayerIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/studio/games/': typeof StudioGamesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/player': typeof PlayerIndexRoute
  '/studio': typeof StudioIndexRoute
  '/studio/games': typeof StudioGamesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/player': typeof PlayerRouteWithChildren
  '/studio': typeof StudioRouteWithChildren
  '/player/': typeof PlayerIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/studio/games/': typeof StudioGamesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/player'
    | '/studio'
    | '/player/'
    | '/studio/'
    | '/studio/games/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/player' | '/studio' | '/studio/games'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/player'
    | '/studio'
    | '/player/'
    | '/studio/'
    | '/studio/games/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PlayerRoute: typeof PlayerRouteWithChildren
  StudioRoute: typeof StudioRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/': {
      id: '/player/'
      path: '/'
      fullPath: '/player/'
      preLoaderRoute: typeof PlayerIndexRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/games/': {
      id: '/studio/games/'
      path: '/games'
      fullPath: '/studio/games/'
      preLoaderRoute: typeof StudioGamesIndexRouteImport
      parentRoute: typeof StudioRoute
    }
  }
}

interface PlayerRouteChildren {
  PlayerIndexRoute: typeof PlayerIndexRoute
}

const PlayerRouteChildren: PlayerRouteChildren = {
  PlayerIndexRoute: PlayerIndexRoute,
}

const PlayerRouteWithChildren =
  PlayerRoute._addFileChildren(PlayerRouteChildren)

interface StudioRouteChildren {
  StudioIndexRoute: typeof StudioIndexRoute
  StudioGamesIndexRoute: typeof StudioGamesIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioIndexRoute: StudioIndexRoute,
  StudioGamesIndexRoute: StudioGamesIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PlayerRoute: PlayerRouteWithChildren,
  StudioRoute: StudioRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
